<?php
/**
 * Copyright © 2018 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var TNW\AuthorizeCim\Block\Payment $block */

$code = $block->escapeHtml($block->getCode());
$payment_config = $block->getPaymentConfig();
?>


<script type="text/x-magento-init">
    {
        "#tnw_authorize_cim_config": {
            "TNW_AuthorizeCim/js/payment": {
                "paymentconfig":<?php /* @noEscape */ echo $block->getPaymentConfig(); ?>
            }
        }
    }
</script>
